### ISSUE TITLE
gc3pie.conf file missing network_ids option

### ISSUE THREAD

**Issue by taleksiev** [uzh/gc3pie#510] opened 2016-02-23 13:39 UTC
The current gc3pie.conf is missing completely the documentation about the network_ids option and will generate the following error when trying to run a work-flow:

"AttributeError: 'OpenStackLrms' object has no attribute 'network_ids'"

**Comment by arcimboldo** [comment] 2016-02-23 16:58
That's probably the cause: https://github.com/uzh/gc3pie/blob/master/gc3libs/backends/openstack.py#L260 the code of `_create_instance` assumes there is an attribute `network_ids` but the constructor does not define it.

**Comment by riccardomurri** [comment] 2018-08-29 13:26
Fixed in #644

**Closed by riccardomurri** 2018-08-29 13:26 UTC
Labels: ready
