### ISSUE TITLE
gc3pie installation on Ubuntu 16.04 runs into missing python packages

### ISSUE THREAD

**Issue by taleksiev** [uzh/gc3pie#581] opened 2016-11-16 10:27 UTC
gc3pie fails during the install process on Ubuntu 16.04:

    :~$ python install.py

    ------
    GC3Pie installation script

    This script installs *latest stable version* of GC3Pie in '/home/ubuntu/gc3pie'.

    If you encounter any problem running this script, please contact
    the GC3Pie team by sending an email to gc3pie@googlegroups.com.

    Remember to attach the full output of the script, in order to help us
    to identify the problem.

    Installation info:

        Destination directory:    /home/ubuntu/gc3pie
        Overwrite existing dir:   ask
        Python executable:        /usr/bin/python
        Ask for confirmation:     yes
        Install unreleased code:  no
        Install gc3apps:          yes
        Optional features:        NONE
        Installer script version: 2.0.2

    Are you ready to continue? [Y/n] y
    Already using interpreter /usr/bin/python
    New python executable in /home/ubuntu/gc3pie/bin/python
    Installing setuptools...................done.
    Installing pip.............done.
    <GC3Pie install>     INFO: Created Python virtual environment in '/home/ubuntu/gc3pie'
    <GC3Pie install>     INFO: Installing GC3Pie released code from PyPI ...
    <GC3Pie install>     INFO: Installing GC3Pie from PyPI package with '/home/ubuntu/gc3pie/bin/pip' ...
    Traceback (most recent call last):
      File "/home/ubuntu/gc3pie/bin/pip", line 11, in <module>
        load_entry_point('pip==8.1.1', 'console_scripts', 'pip')()
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565, in load_entry_point
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2631, in load_entry_point
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2291, in load
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2297, in resolve
      File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 13, in <module>
        from pip.exceptions import InstallationError, CommandError, PipError
      File "/usr/lib/python2.7/dist-packages/pip/exceptions.py", line 6, in <module>
        from pip._vendor.six import iteritems
    ImportError: No module named six
    Traceback (most recent call last):
      File "install.py", line 982, in <module>
        main()
      File "install.py", line 137, in main
        install_gc3pie_from_pypi(options.target, options.features)
      File "install.py", line 720, in install_gc3pie_from_pypi
        .format(features_for_pip=str.join(' ', features), **locals()))
      File "install.py", line 956, in run_in_virtualenv
        check_call(cmd, shell=True)
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '. /home/ubuntu/gc3pie/bin/activate; pip install 'gc3pie'' returned non-zero exit status 1

Current work around is the installation of the following packages: 
python-{six,ipaddr,retrying,progress,requests,cachecontrol,lockfile,distlib,packaging,html5lib}

**Comment by riccardomurri** [comment] 2016-11-23 16:11
(taleksiev, Wed, Nov 16, 2016 at 02:27:18AM -0800:)
> gc3pie fails during the install process on Ubuntu 16.04:

I cannot reproduce this; I have tried on a VM on Science Cloud,
installed from image "Ubuntu Server 16.04.1 LTS (2016-09-27) +
python2.7" (UUID: 0ee2a4ff-22b8-44e1-8d4c-4cf57f9c6c47)::

    ubuntu@gc3pie-on-16:~$ sudo apt install python-dev gcc g++ libffi-dev libssl-dev
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      linux-headers-4.4.0-34 linux-headers-4.4.0-34-generic linux-image-4.4.0-34-generic
    Use 'sudo apt autoremove' to remove them.
    The following additional packages will be installed:
      binutils cpp cpp-5 g++-5 gcc-5 libasan2 libatomic1 libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libexpat1-dev libgcc-5-dev libgomp1 libisl15 libitm1 liblsan0 libmpc3 libmpx0
      libpython-dev libpython2.7 libpython2.7-dev libquadmath0 libssl-doc libstdc++-5-dev libtsan0 libubsan0 linux-libc-dev manpages-dev python2.7-dev zlib1g-dev
    Suggested packages:
      binutils-doc cpp-doc gcc-5-locales g++-multilib g++-5-multilib gcc-5-doc libstdc++6-5-dbg gcc-multilib make autoconf automake libtool flex bison gdb gcc-doc gcc-5-multilib libgcc1-dbg
      libgomp1-dbg libitm1-dbg libatomic1-dbg libasan2-dbg liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg libmpx0-dbg libquadmath0-dbg glibc-doc libstdc++-5-doc
    The following NEW packages will be installed:
      binutils cpp cpp-5 g++ g++-5 gcc gcc-5 libasan2 libatomic1 libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libexpat1-dev libffi-dev libgcc-5-dev libgomp1 libisl15 libitm1 liblsan0 libmpc3
      libmpx0 libpython-dev libpython2.7 libpython2.7-dev libquadmath0 libssl-dev libssl-doc libstdc++-5-dev libtsan0 libubsan0 linux-libc-dev manpages-dev python-dev python2.7-dev zlib1g-dev
    0 upgraded, 36 newly installed, 0 to remove and 0 not upgraded.
    Need to get 61.4 MB/69.2 MB of archives.
    After this operation, 195 MB of additional disk space will be used.
    Do you want to continue? [Y/n] 
    Get:1 http://nova.clouds.archive.ubuntu.com/ubuntu xenial-updates/main amd64 cpp-5 amd64 5.4.0-6ubuntu1~16.04.4 [7653 kB]
    ...
    Setting up libffi-dev:amd64 (3.2.1-4) ...
    Processing triggers for libc-bin (2.23-0ubuntu4) ...


    ubuntu@gc3pie-on-16:~$ python install.py
    ==========================
    GC3Pie installation script
    ==========================

    This script installs *latest stable version* of GC3Pie in '/home/ubuntu/gc3pie'.

    If you encounter any problem running this script, please contact
    the GC3Pie team by sending an email to gc3pie@googlegroups.com.

    Remember to attach the full output of the script, in order to help us
    to identify the problem.

    Installation info:

        Destination directory:    /home/ubuntu/gc3pie
        Overwrite existing dir:   ask
        Python executable:        /usr/bin/python
        Ask for confirmation:     yes
        Install unreleased code:  no
        Install gc3apps:          yes
        Optional features:        NONE
        Installer script version: 2.0.2


    Are you ready to continue? [Y/n] 
    Already using interpreter /usr/bin/python
    New python executable in /home/ubuntu/gc3pie/bin/python
    Installing setuptools..............................done.
    Installing pip.................................done.
    <GC3Pie install>     INFO: Created Python virtual environment in '/home/ubuntu/gc3pie'
    <GC3Pie install>     INFO: Trying to install or upgrade setuptools ...
    <GC3Pie install>     INFO: `easy_install` is available, using it to upgrade setuptools
    Searching for setuptools
    Reading http://pypi.python.org/simple/setuptools/
    Best match: setuptools 28.8.0
    Processing setuptools-28.8.0-py2.7.egg
    Removing setuptools 0.6c11 from easy-install.pth file
    Adding setuptools 28.8.0 to easy-install.pth file
    Installing easy_install script to /home/ubuntu/gc3pie/bin
    Installing easy_install-2.7 script to /home/ubuntu/gc3pie/bin

    Using /home/ubuntu/gc3pie/lib/python2.7/site-packages/setuptools-28.8.0-py2.7.egg
    Processing dependencies for setuptools
    Finished processing dependencies for setuptools
    <GC3Pie install>     INFO: Installing GC3Pie released code from PyPI ...
    <GC3Pie install>     INFO: Installing GC3Pie from PyPI package with '/home/ubuntu/gc3pie/bin/pip' ...
    Collecting gc3pie
      Downloading gc3pie-2.4.2.tar.gz (546kB)
        100% |################################| 552kB 2.1MB/s 
    Collecting paramiko (from gc3pie)
      Downloading paramiko-2.0.2-py2.py3-none-any.whl (171kB)
        100% |################################| 174kB 6.6MB/s 
    Collecting pycrypto (from gc3pie)
      Downloading pycrypto-2.6.1.tar.gz (446kB)
        100% |################################| 450kB 2.0MB/s 
    Collecting prettytable (from gc3pie)
      Downloading prettytable-0.7.2.zip
    Collecting pyCLI (from gc3pie)
      Downloading pyCLI-2.0.3.tar.gz (49kB)
        100% |################################| 51kB 6.5MB/s 
    Collecting sqlalchemy (from gc3pie)
      Downloading SQLAlchemy-1.1.4.tar.gz (5.1MB)
        100% |################################| 5.1MB 189kB/s 
    Collecting parsedatetime (from gc3pie)
      Downloading parsedatetime-2.1-py2-none-any.whl
    Collecting pyasn1>=0.1.7 (from paramiko->gc3pie)
      Downloading pyasn1-0.1.9-py2.py3-none-any.whl
    Collecting cryptography>=1.1 (from paramiko->gc3pie)
      Downloading cryptography-1.6.tar.gz (410kB)
        100% |################################| 419kB 2.2MB/s 
    Collecting idna>=2.0 (from cryptography>=1.1->paramiko->gc3pie)
      Downloading idna-2.1-py2.py3-none-any.whl (54kB)
        100% |################################| 61kB 6.9MB/s 
    Collecting six>=1.4.1 (from cryptography>=1.1->paramiko->gc3pie)
      Downloading six-1.10.0-py2.py3-none-any.whl
    Requirement already satisfied: setuptools>=11.3 in ./gc3pie/lib/python2.7/site-packages/setuptools-28.8.0-py2.7.egg (from cryptography>=1.1->paramiko->gc3pie)
    Collecting enum34 (from cryptography>=1.1->paramiko->gc3pie)
      Downloading enum34-1.1.6-py2-none-any.whl
    Collecting ipaddress (from cryptography>=1.1->paramiko->gc3pie)
      Downloading ipaddress-1.0.17-py2-none-any.whl
    Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko->gc3pie)
      Downloading cffi-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl (387kB)
        100% |################################| 389kB 2.2MB/s 
    Collecting pycparser (from cffi>=1.4.1->cryptography>=1.1->paramiko->gc3pie)
      Downloading pycparser-2.17.tar.gz (231kB)
        100% |################################| 235kB 3.7MB/s 
    Installing collected packages: pyasn1, idna, six, enum34, ipaddress, pycparser, cffi, cryptography, paramiko, pycrypto, prettytable, pyCLI, sqlalchemy, parsedatetime, gc3pie
      Running setup.py install for pycparser ... done
      Running setup.py install for cryptography ... done
      Running setup.py install for pycrypto ... done
      Running setup.py install for prettytable ... done
      Running setup.py install for pyCLI ... done
      Running setup.py install for sqlalchemy ... done
      Running setup.py install for gc3pie ... done
    Successfully installed cffi-1.9.1 cryptography-1.6 enum34-1.1.6 gc3pie-2.4.2 idna-2.1 ipaddress-1.0.17 paramiko-2.0.2 parsedatetime-2.1 prettytable-0.7.2 pyCLI-2.0.3 pyasn1-0.1.9 pycparser-2.17 pycrypto-2.6.1 six-1.10.0 sqlalchemy-1.1.4
    <GC3Pie install>     INFO: Installing extra applications into '/home/ubuntu/gc3pie/bin' ...
    <GC3Pie install>     INFO:   /home/ubuntu/gc3pie/gc3apps/grundb.py -> /home/ubuntu/gc3pie/bin/grundb.py
    <GC3Pie install>     INFO:   /home/ubuntu/gc3pie/gc3apps/gridrun.py -> /home/ubuntu/gc3pie/bin/gridrun.py
    <GC3Pie install>     INFO:   /home/ubuntu/gc3pie/gc3apps/gcodeml.py -> /home/ubuntu/gc3pie/bin/gcodeml.py
    <GC3Pie install>     INFO:   /home/ubuntu/gc3pie/gc3apps/ggamess.py -> /home/ubuntu/gc3pie/bin/ggamess.py

    ===============================
    Installation of GC3Pie is done!
    ===============================

    In order to work with GC3Pie you have to enable the virtual
    environment with the command:

        . /home/ubuntu/gc3pie/bin/activate

    You need to run the above command on every new shell you open before
    using GC3Pie commands, but just once per session.

    If the shell's prompt starts with '(gc3pie)' it means that the virtual
    environment has been enabled.

The virtual environment is set up correctly::

    ubuntu@gc3pie-on-16:~$ . /home/ubuntu/gc3pie/bin/activate
    (gc3pie)ubuntu@gc3pie-on-16:~$ gservers 
    gc3.gc3utils: WARNING: No configuration file '/home/ubuntu/.gc3/gc3pie.conf' was found; a sample one has been copied in that location; please edit it and define resources.
    +---------------------+--------------------------+-----------+
    |                     | localhost                |           |
    +---------------------+--------------------------+-----------+
    |            frontend | ( Frontend host name )   | localhost |
    |                type | ( Access mode )          | shellcmd  |
    |             updated | ( Accessible? )          | True      |
    |              queued | ( Total queued jobs )    | 0         |
    |         user_queued | ( Own queued jobs )      | 0         |
    |            user_run | ( Own running jobs )     | 0         |
    |   max_cores_per_job | ( Max cores per job )    | 2         |
    | max_memory_per_core | ( Max memory per core )  | 2GB       |
    |        max_walltime | ( Max walltime per job ) | 2hour     |
    +---------------------+--------------------------+-----------+

-- 
Riccardo Murri, Schwerzenbacherstrasse 2, CH-8606 Nänikon, Switzerland

**Comment by riccardomurri** [comment] 2016-11-23 16:19
Same result with `python install.py --overwrite -a openstack --yes -D`,
i.e. GC3Pie successfully installed.

**Comment by riccardomurri** [comment] 2016-11-23 16:28
Also installed successfully if `pip` and `virtualenv` are installed system-wide with Ubuntu packages `python-pip` and `python-virtualenv`.

**Comment by riccardomurri** [comment] 2016-11-23 16:29
I think this is/was a local problem.  I'm marking it as invalid and closing.

Please re-open if there is any further evidence.

**Closed by riccardomurri** 2016-11-23 16:29 UTC
Labels: Installation, not an issue
